# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginlanding', '0002_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facilityID', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('user', models.PositiveIntegerField()),
            ],
        ),
    ]
