# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginlanding', '0002_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='facilityType',
            field=models.CharField(choices=[('0', 'Library'), ('1', 'University'), ('2', 'Hotel'), ('3', 'Industry'), ('4', 'Zoo'), ('5', 'Park'), ('6', 'Museum'), ('7', 'Mall'), ('8', 'Restaurant')], max_length=1),
        ),
    ]
