# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171019_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('0', 'Student'), ('1', 'Tourist'), ('2', 'Business')], max_length=1),
        ),
    ]
